<?php
/**
 * layout.phtml
 * @copyright Copyright © 2015 cloud-nemo
 * @author    cloud-nemo
 */
$baseUrl = $this->baseUrl();
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
        <title><?php echo $this->title ?></title>
        <link href="<?php echo $baseUrl ?>css/base.css" media="screen" rel="stylesheet" type="text/css">
        <link href="<?php echo $baseUrl ?>image/favicon.ico" rel="shortcut icon" type="image/x-icon">
        <script src="<?php echo $baseUrl ?>js/website.js" type="text/javascript"></script>
    </head>
    <body>
        <header class="heading">
            <nav id="main-nav">
                <span><a class="home-link" href="<?php echo $baseUrl ?>">HOME</a></span>
            </nav>
        </header>
        <main>
            <div id="content">
                <?php echo $this->content ?>
            </div>
        </main>
        <footer class="footer">
            <nav id="footer-nav">
                <span></span>
            </nav>
        </footer>
    <?php echo html_entity_decode(
        '&lt;div id=&quot;selectedOrganizersCheckbox&quot;&gt;&#10;&lt;input type=&quot;hidden&quot; name=&quot;optOrganizer&quot; value=&quot;0&quot; /&gt;&lt;input type=&quot;checkbox&quot; name=&quot;optOrganizer&quot; id=&quot;optOrganizer&quot; value=&quot;ULT;FER;FTI&quot; checked=&quot;checked&quot; class=&quot;selectedOrganizers&quot; /&gt;&#10;&lt;span id=&quot;selectedOrganizers-label&quot;&gt;&lt;label for=&quot;selectedOrganizers&quot; class=&quot;optional&quot;&gt;Nur Angebote von FERIEN Touristik, FTI Touristik, Urlaubstours zeigen&lt;/label&gt;&lt;/span&gt;&lt;/div&gt;'
    ); ?>
    </body>
</html>