<?php
/**
 * error.phtml
 * @copyright Copyright © 2015 cloud-nemo
 * @author    cloud-nemo
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->title ?></title>
    <link href="<?php echo $this->baseUrl() ?>css/base.css" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->baseUrl() ?>image/favicon.ico" rel="shortcut icon" type="image/x-icon">
</head>
<body>
    <div id="content">
        <?php echo $this->error ?>
    </div>
</body>
</html>